name: flod
description: Strict, fast, type-safe data validation and transformation for Dart and Flutter.
version: 1.1.1
repository: https://github.com/leeerrrrmmm/Flod-Library/tree/main/flod

environment:
  sdk: ^3.12.0

dependencies:
  meta: ^1.12.0
  dio: ^5.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

